import { jsPDF } from "jspdf"

interface ShipmentData {
  bookingRef: string
  sapRef: string
  origin: string
  destination: string
  carrier: string
  vessel: string
  sailing: string
  containerType: string
  plant: string
  mode: string
}

const DEFAULT_DATA: ShipmentData = {
  bookingRef: "MAEU-2024-SHA-78432",
  sapRef: "SAP-TM-87234",
  origin: "Shanghai (CNSHA)",
  destination: "Los Angeles (USLAX)",
  carrier: "Maersk Line",
  vessel: "AE-1234 (Ever Given)",
  sailing: "Mar 22, 2024",
  containerType: "2×40' High Cube",
  plant: "Suzhou Plant",
  mode: "Ocean FCL",
}

function addHeader(doc: jsPDF, title: string) {
  // Blue header bar
  doc.setFillColor(30, 58, 95)
  doc.rect(0, 0, 210, 25, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.text("Zero Touch Booking Agent", 15, 12)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("Automated Freight Documentation", 15, 18)

  // Document title
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text(title, 15, 38)

  // Divider line
  doc.setDrawColor(200, 200, 200)
  doc.line(15, 42, 195, 42)
}

function addField(doc: jsPDF, label: string, value: string, x: number, y: number) {
  doc.setTextColor(120, 120, 120)
  doc.setFontSize(8)
  doc.setFont("helvetica", "normal")
  doc.text(label, x, y)
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(10)
  doc.setFont("helvetica", "bold")
  doc.text(value, x, y + 5)
}

function addFooter(doc: jsPDF, data: ShipmentData) {
  const y = 270
  doc.setDrawColor(200, 200, 200)
  doc.line(15, y, 195, y)
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(7)
  doc.setFont("helvetica", "normal")
  doc.text(`Booking Ref: ${data.bookingRef}  |  SAP Ref: ${data.sapRef}  |  Generated by Zero Touch Booking Agent`, 15, y + 5)
  doc.text(`Generated: ${new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" })} ${new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })}`, 15, y + 9)
}

export function generateSLI(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Shipper's Letter of Instruction")

  let y = 50

  // Reference info
  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", data.bookingRef, 20, y + 6)
  addField(doc, "SAP Order Reference", data.sapRef, 100, y + 6)

  y += 28

  // Shipper / Consignee
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Shipper Information", 15, y)
  y += 8
  addField(doc, "Company", `${data.plant} — Electronics Division`, 15, y)
  addField(doc, "Address", "No. 88 Industrial Park, Suzhou, Jiangsu 215000, China", 100, y)
  y += 14
  addField(doc, "Contact", "Li Wei, Export Manager", 15, y)
  addField(doc, "Phone", "+86 512 6688 7799", 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Consignee Information", 15, y)
  y += 8
  addField(doc, "Company", "Global Electronics Corp.", 15, y)
  addField(doc, "Address", "1200 Harbor Blvd, Los Angeles, CA 90012, USA", 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Routing Instructions", 15, y)
  y += 8
  addField(doc, "Carrier", data.carrier, 15, y)
  addField(doc, "Vessel / Voyage", data.vessel, 100, y)
  y += 14
  addField(doc, "Port of Loading", data.origin, 15, y)
  addField(doc, "Port of Discharge", data.destination, 100, y)
  y += 14
  addField(doc, "Sailing Date", data.sailing, 15, y)
  addField(doc, "Container Type", data.containerType, 100, y)
  y += 14
  addField(doc, "Incoterm", "FOB Shanghai", 15, y)
  addField(doc, "Transport Mode", data.mode, 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Description of Goods", 15, y)
  y += 8
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("Electronic components and laptop parts (HS 8471.30)", 15, y)
  doc.text("Gross Weight: 18,400 kg  |  Net Weight: 17,200 kg  |  Packages: 240 cartons", 15, y + 5)

  y += 20
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Special Instructions", 15, y)
  y += 7
  doc.setTextColor(80, 80, 80)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("1. Handle with care — fragile electronic components", 15, y)
  doc.text("2. Temperature-controlled storage not required", 15, y + 5)
  doc.text("3. Standard ocean freight — no hazardous materials", 15, y + 10)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}

export function generatePackingList(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Commercial Packing List")

  let y = 50

  // Reference
  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", data.bookingRef, 20, y + 6)
  addField(doc, "Invoice No.", "INV-2024-SZ-04821", 100, y + 6)

  y += 28
  addField(doc, "Shipper", `${data.plant}`, 15, y)
  addField(doc, "Consignee", "Global Electronics Corp., Los Angeles", 100, y)

  y += 16

  // Items table
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Packing Details", 15, y)
  y += 6

  // Table header
  doc.setFillColor(30, 58, 95)
  doc.rect(15, y, 180, 8, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  const cols = [15, 30, 85, 115, 140, 165]
  doc.text("#", cols[0] + 2, y + 5.5)
  doc.text("Description", cols[1] + 2, y + 5.5)
  doc.text("Qty", cols[2] + 2, y + 5.5)
  doc.text("Net Wt (kg)", cols[3] + 2, y + 5.5)
  doc.text("Gross Wt (kg)", cols[4] + 2, y + 5.5)
  doc.text("Dims (cm)", cols[5] + 2, y + 5.5)

  y += 8

  const items = [
    ["1", "Laptop Motherboards (HS 8471.30)", "120 pcs", "4,200", "4,600", "60×40×30"],
    ["2", "LCD Display Panels (HS 8528.52)", "80 pcs", "3,400", "3,800", "55×35×25"],
    ["3", "SSD Storage Modules (HS 8471.70)", "200 pcs", "2,800", "3,000", "40×30×20"],
    ["4", "Battery Packs (HS 8507.60)", "160 pcs", "3,600", "3,900", "50×35×25"],
    ["5", "Keyboard Assemblies (HS 8471.60)", "120 pcs", "1,800", "2,000", "45×30×15"],
    ["6", "Power Adapters (HS 8504.40)", "240 pcs", "1,400", "1,700", "30×20×15"],
  ]

  items.forEach((item, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 249, 252)
      doc.rect(15, y, 180, 7, "F")
    }
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(8)
    doc.setFont("helvetica", "normal")
    item.forEach((val, ci) => {
      doc.text(val, cols[ci] + 2, y + 5)
    })
    y += 7
  })

  // Totals
  y += 4
  doc.setDrawColor(30, 58, 95)
  doc.line(115, y, 195, y)
  y += 6
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(30, 58, 95)
  doc.text("Total Packages:", 115, y)
  doc.text("240 cartons", 165, y)
  y += 6
  doc.text("Total Net Weight:", 115, y)
  doc.text("17,200 kg", 165, y)
  y += 6
  doc.text("Total Gross Weight:", 115, y)
  doc.text("18,400 kg", 165, y)

  y += 12
  addField(doc, "Container", data.containerType, 15, y)
  addField(doc, "Marks & Numbers", `MK: GEC-SZ-${data.bookingRef.slice(-5)}`, 100, y)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}

export function generateCustomsDeclaration(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Customs Declaration (AES)")

  let y = 50

  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "AES ITN", "X20240322-87234-001", 20, y + 6)
  addField(doc, "Booking Reference", data.bookingRef, 100, y + 6)

  y += 28
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Export Information", 15, y)
  y += 8

  addField(doc, "Exporter (USPPI)", `${data.plant} — Electronics Division`, 15, y)
  addField(doc, "EIN", "91-2345678", 140, y)
  y += 14
  addField(doc, "Ultimate Consignee", "Global Electronics Corp.", 15, y)
  addField(doc, "Country of Destination", "United States", 140, y)

  y += 16
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Commodity Details", 15, y)
  y += 6

  // HS code table
  doc.setFillColor(30, 58, 95)
  doc.rect(15, y, 180, 8, "F")
  doc.setTextColor(255)
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  doc.text("HS Code", 17, y + 5.5)
  doc.text("Description", 50, y + 5.5)
  doc.text("Value (USD)", 130, y + 5.5)
  doc.text("Origin", 170, y + 5.5)
  y += 8

  const commodities = [
    ["8471.30", "Laptop Motherboards", "$84,000", "China"],
    ["8528.52", "LCD Display Panels", "$62,400", "China"],
    ["8471.70", "SSD Storage Modules", "$56,000", "China"],
    ["8507.60", "Lithium Battery Packs", "$48,000", "China"],
    ["8471.60", "Keyboard Assemblies", "$14,400", "China"],
    ["8504.40", "Power Adapters", "$19,200", "China"],
  ]

  commodities.forEach((item, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 249, 252)
      doc.rect(15, y, 180, 7, "F")
    }
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(8)
    doc.setFont("helvetica", "normal")
    doc.text(item[0], 17, y + 5)
    doc.text(item[1], 50, y + 5)
    doc.text(item[2], 130, y + 5)
    doc.text(item[3], 170, y + 5)
    y += 7
  })

  y += 6
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(30, 58, 95)
  doc.text("Total Declared Value:", 100, y)
  doc.text("$284,000 USD", 155, y)

  y += 14
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Certifications", 15, y)
  y += 8
  doc.setTextColor(80, 80, 80)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("I declare that all statements made and all information contained herein are true and correct.", 15, y)
  y += 5
  doc.text("No dangerous goods or prohibited items are included in this shipment.", 15, y)
  y += 5
  doc.text("Export License: NLR (No License Required)", 15, y)

  y += 14
  addField(doc, "Date", new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" }), 15, y)
  addField(doc, "Authorized Signature", "________________________", 100, y)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}
